name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    if: github.repository	== "MikeDev96/lucille-bot"
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            [ -d "/home/migul/Documents/LucilleBot" ] && cd /home/migul/Documents/LucilleBot && git pull || git clone https://github.com/MikeDev96/lucille-bot.git
