name: CI-CD

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-deploy notification to Lucille
        if: github.repository == 'MikeDev96/lucille-bot'
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'POST'
          contentType: 'application/json'
          data: ${{ secrets.WEBHOOK_PRE_DEPLOY_PAYLOAD }}
          
      - name: Pre-deploy notification to null;
        if: github.repository == 'MikeDev96/lucille-bot'
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL_NULL }}
          method: 'POST'
          contentType: 'application/json'
          data: ${{ secrets.WEBHOOK_PRE_DEPLOY_PAYLOAD }}

      - name: Deploy
        if: github.repository == 'MikeDev96/lucille-bot'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            function changed {
              cd /var/www/lucille-bot && git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
            }

            if changed 'package-lock.json'; then
              [ -d "/var/www/lucille-bot" ] && cd /var/www/lucille-bot && git pull && npm ci && pm2 reload lucille
            else 
              [ -d "/var/www/lucille-bot" ] && cd /var/www/lucille-bot && git pull && pm2 reload lucille
            fi
          
      - name: Post-deploy notification to Lucille
        if: github.repository == 'MikeDev96/lucille-bot'
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'POST'
          contentType: 'application/json'
          data: ${{ secrets.WEBHOOK_POST_DEPLOY_PAYLOAD }}

      - name: Post-deploy notification to null;
        if: github.repository == 'MikeDev96/lucille-bot'
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL_NULL }}
          method: 'POST'
          contentType: 'application/json'
          data: ${{ secrets.WEBHOOK_POST_DEPLOY_PAYLOAD }}
